name: Module tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.6', '3.7', '3.8', '3.9', '3.10']
        django-version: ['2.2', '3.1', '3.2']
        experimental: [false]
        include:
          - python-version: pypy3
            django-version: '2.2'
            experimental: true
          - python-version: pypy3
            django-version: '3.2'
            experimental: true
          

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Django ${{ matrix.django-version }}
        run: pip install 'Django==${{ matrix.django-version }}'

      - name: Install django_userforeignkey
        run: pip install .

      - name: Run tests
        continue-on-error: ${{ matrix.experimental }}
        run: cd tests/ && python manage.py test
